/* research(trustmrr)+App Store 분해 · 6축 카드 · 도메인 태그(d) 포함 */
var AXES=[
{key:'who',ko:'누가',question:'누구를 도울까?',glyph:'👤',cards:[
 {label:'과제 많은 대학생',keywords:'대학생·과제',d:'learn'},
 {label:'면접 앞둔 취준생',keywords:'취준·면접',d:'work'},
 {label:'이력서 넣는 구직자',keywords:'구직·이력서',d:'work'},
 {label:'프로필 필요한 직장인',keywords:'직장인·프로필',d:'image'},
 {label:'스타일 고민하는 사람',keywords:'스타일·뷰티',d:'image'},
 {label:'그림 그리는 디자이너',keywords:'디자인·일러스트',d:'image'},
 {label:'1인 쇼핑몰 사장',keywords:'셀러·쇼핑몰',d:'biz'},
 {label:'로고 필요한 1인 창업자',keywords:'창업·브랜드',d:'image'},
 {label:'SNS 키우고 싶은 사람',keywords:'SNS·계정',d:'content'},
 {label:'유튜브 크리에이터',keywords:'유튜버·영상',d:'content'},
 {label:'동네 작은 가게 사장',keywords:'소상공인·사장님',d:'biz'},
 {label:'유행 좇는 마케터',keywords:'마케터·유행',d:'biz'},
 {label:'자동화 원하는 1인 개발자',keywords:'개발·자동화',d:'work'},
 {label:'행사 준비하는 사람',keywords:'행사·준비',d:'work'},
 {label:'뭐 살지 고민하는 사람',keywords:'쇼핑·비교',d:'shop'},
 {label:'동네 동호회 총무',keywords:'동호회·모임',d:'money'},
 {label:'채용 담당자',keywords:'채용·인사',d:'work'},
 {label:'집 꾸미고 싶은 사람',keywords:'인테리어·집',d:'image'},
 {label:'프리랜서·1인 사업가',keywords:'프리랜서·1인',d:'biz'},
 {label:'외국어 배우는 사람',keywords:'어학·학습',d:'learn'},
 {label:'운동 시작한 초보',keywords:'헬스·홈트',d:'health'},
 {label:'다이어트 중인 사람',keywords:'식단·칼로리',d:'health'},
 {label:'돈 관리하는 사람',keywords:'가계부·지출',d:'money'},
 {label:'숏폼 올리는 사람',keywords:'릴스·숏폼',d:'content'},
 {label:'손글씨 필기하는 학생',keywords:'필기·노트',d:'learn'},
 {label:'가족 일정 챙기는 엄마',keywords:'가족·일정',d:'life'},
 {label:'혼자라 외로운 사람',keywords:'외로움·대화',d:'life'},
 {label:'재테크 시작한 초보',keywords:'재테크·투자',d:'money'},
 {label:'회의 많은 직장인',keywords:'회의·기록',d:'work'},
 {label:'운세 궁금한 사람',keywords:'사주·운세',d:'life'},
 {label:'습관 만들려는 사람',keywords:'습관·루틴',d:'learn'},
 {label:'하루 기분 남기는 사람',keywords:'일기·기분',d:'life'},
 {label:'중고 거래하는 사람',keywords:'중고·거래',d:'shop'},
 {label:'한정판 노리는 사람',keywords:'한정판·수집',d:'shop'},
 {label:'수학 어려운 학생',keywords:'수학·문제',d:'learn'},
 {label:'뉴스 챙기는 직장인',keywords:'뉴스·시사',d:'work'}]},
{key:'pain',ko:'고민',question:'뭐가 불편할까?',glyph:'😟',cards:[
 {label:'어디부터 할지 막막해요',keywords:'막막·시작',d:'general'},
 {label:'만들 시간이 없어요',keywords:'시간·바쁨',d:'general'},
 {label:'돈 들여 만들기 부담돼요',keywords:'비용·부담',d:'general'},
 {label:'돈이 어디로 새는지 몰라요',keywords:'지출·가계부',d:'money'},
 {label:'팔로워가 안 늘어요',keywords:'SNS·성장',d:'content'},
 {label:'만든 걸 아무도 몰라요',keywords:'홍보·노출',d:'biz'},
 {label:'손님을 어디서 찾죠',keywords:'고객·영업',d:'biz'},
 {label:'손님이 못 믿고 안 사요',keywords:'신뢰·구매',d:'biz'},
 {label:'후기·의견 모으기 힘들어요',keywords:'후기·수집',d:'biz'},
 {label:'뭘 골라야 할지 모르겠어요',keywords:'비교·선택',d:'shop'},
 {label:'반복 작업이 너무 벅차요',keywords:'반복·귀찮',d:'work'},
 {label:'편집이 너무 어려워요',keywords:'편집·초보',d:'content'},
 {label:'자꾸 까먹어요',keywords:'기억·메모',d:'work'},
 {label:'집중이 자꾸 흐트러져요',keywords:'집중·산만',d:'work'},
 {label:'뭐부터 할지 순서가 안 서요',keywords:'할일·우선순위',d:'work'},
 {label:'뭐가 유행인지 모르겠어요',keywords:'유행·정보',d:'content'},
 {label:'일이 여기저기 흩어져요',keywords:'정리·관리',d:'work'},
 {label:'바꾼 모습이 상상 안 돼요',keywords:'미리보기·불안',d:'image'},
 {label:'나한테 맞는 걸 모르겠어요',keywords:'취향·추천',d:'general'},
 {label:'팔리는 글이 안 써져요',keywords:'글쓰기·카피',d:'biz'},
 {label:'긴 영상 자르기 힘들어요',keywords:'영상·편집',d:'content'},
 {label:'썸네일 만들기가 어려워요',keywords:'썸네일·디자인',d:'content'},
 {label:'먹은 걸 세기 귀찮아요',keywords:'칼로리·기록',d:'health'},
 {label:'돈 계산·정산이 헷갈려요',keywords:'정산·계산',d:'money'},
 {label:'맞춤법이 자꾸 틀려요',keywords:'맞춤법·오타',d:'work'},
 {label:'운동 자세를 모르겠어요',keywords:'자세·운동',d:'health'},
 {label:'혼자라 얘기할 사람 없어요',keywords:'외로움·대화',d:'life'},
 {label:'종이 서류가 자꾸 쌓여요',keywords:'서류·정리',d:'work'},
 {label:'이메일 쓰기 시간 걸려요',keywords:'메일·시간',d:'work'},
 {label:'작심삼일로 끝나요',keywords:'습관·꾸준',d:'learn'},
 {label:'내 운세가 궁금해요',keywords:'운세·미래',d:'life'},
 {label:'며칠 남았는지 세기 귀찮아요',keywords:'날짜·계산',d:'general'},
 {label:'사진이 밋밋해요',keywords:'사진·보정',d:'image'},
 {label:'그림을 못 그려요',keywords:'그림·재능',d:'image'},
 {label:'무슨 일 났는지 늦게 알아요',keywords:'뒷북·실시간',d:'general'},
 {label:'사기당할까 걱정돼요',keywords:'거래·불안',d:'shop'}]},
{key:'how',ko:'방법',question:'어떻게 도울까?',glyph:'🛠',cards:[
 {label:'AI가 초안 써주기',keywords:'AI·초안',d:'general'},
 {label:'사진 올리면 바꿔주기',keywords:'사진·변환',d:'image'},
 {label:'미리 입혀 보여주기',keywords:'미리보기·시뮬',d:'shop'},
 {label:'몇 초 만에 만들어주기',keywords:'빠르게·생성',d:'general'},
 {label:'사진·영상 자동으로 뽑아주기',keywords:'자동·콘텐츠',d:'content'},
 {label:'대신 댓글·답글 달아주기',keywords:'댓글·자동',d:'content'},
 {label:'흩어진 걸 한곳에 모아주기',keywords:'모으기·정리',d:'work'},
 {label:'여러 개 비교해 보여주기',keywords:'비교·추천',d:'shop'},
 {label:'후기를 화면에 띄워주기',keywords:'후기·노출',d:'shop'},
 {label:'반복 작업 대신 해주기',keywords:'자동화·반복',d:'work'},
 {label:'몇 명 봤는지 세어주기',keywords:'집계·통계',d:'content'},
 {label:'유행 흐름 추적해주기',keywords:'유행·추적',d:'content'},
 {label:'사람들에게 보여주기',keywords:'노출·홍보',d:'general'},
 {label:'실시간으로 알려주기',keywords:'실시간·알림',d:'general'},
 {label:'긴 영상 짧게 잘라주기',keywords:'영상·편집',d:'content'},
 {label:'글만 쓰면 그림으로 그려주기',keywords:'자동·시각화',d:'image'},
 {label:'시간 재며 집중 도와주기',keywords:'타이머·집중',d:'work'},
 {label:'AI가 대신 기억해주기',keywords:'AI·기억',d:'work'},
 {label:'AI로 사진 보정해주기',keywords:'AI·사진보정',d:'image'},
 {label:'맞춤 계획 짜주기',keywords:'AI·맞춤',d:'general'},
 {label:'사진 찍으면 알아서 인식하기',keywords:'사진인식·자동',d:'general'},
 {label:'카드뉴스 자동으로 만들어주기',keywords:'자동·디자인',d:'content'},
 {label:'돈 들어온 걸 한눈에 모아주기',keywords:'매출·정리',d:'money'},
 {label:'채팅으로 코치처럼 챙겨주기',keywords:'챗봇·코칭',d:'general'},
 {label:'정해둔 시간에 알림 보내기',keywords:'알림·시간',d:'general'},
 {label:'틀린 부분 바로 고쳐주기',keywords:'교정·즉시',d:'learn'},
 {label:'손글씨 자동으로 정리해주기',keywords:'필기·정리',d:'learn'},
 {label:'사진 찍으면 문서로 바꾸기',keywords:'스캔·변환',d:'work'},
 {label:'사진 찍으면 칼로리 계산하기',keywords:'사진·칼로리',d:'health'},
 {label:'말하면 자동으로 요약하기',keywords:'회의·요약',d:'work'},
 {label:'AI가 말동무 되어주기',keywords:'AI·대화',d:'life'},
 {label:'나눠서 결제하게 해주기',keywords:'분할·결제',d:'money'},
 {label:'어려운 걸 쉽게 풀어주기',keywords:'요약·해설',d:'learn'},
 {label:'검수해서 정품 보장하기',keywords:'검수·보장',d:'shop'},
 {label:'단계별로 차근차근 알려주기',keywords:'단계·학습',d:'learn'},
 {label:'따라 할 영상 보여주기',keywords:'영상·따라하기',d:'general'}]},
{key:'form',ko:'모양',question:'어떤 모습으로?',glyph:'🎴',cards:[
 {label:'사진 올리면 결과 나오는 화면',keywords:'업로드·결과',d:'general'},
 {label:'물어보면 답하는 챗봇',keywords:'챗봇·대화',d:'general'},
 {label:'버튼 누르면 초안 나오는 화면',keywords:'버튼·생성',d:'general'},
 {label:'스타일 골라보는 미리보기',keywords:'미리보기·선택',d:'image'},
 {label:'핵심만 보여주는 통계 화면',keywords:'심플·통계',d:'general'},
 {label:'유행 순위 보여주는 목록',keywords:'랭킹·목록',d:'content'},
 {label:'비교표 사이트',keywords:'비교표·웹',d:'shop'},
 {label:'사이트에 뜨는 알림 팝업',keywords:'팝업·알림',d:'general'},
 {label:'후기 모아 보여주는 위젯',keywords:'후기·위젯',d:'shop'},
 {label:'반복일 대신하는 자동화 화면',keywords:'자동화·봇',d:'work'},
 {label:'할 일 정리 대시보드',keywords:'할일·정렬',d:'work'},
 {label:'집중 타이머 앱',keywords:'타이머·집중',d:'work'},
 {label:'생각 적는 메모장',keywords:'메모·심플',d:'work'},
 {label:'내 소개 한 페이지',keywords:'페이지·프로필',d:'general'},
 {label:'짧은 영상 만드는 화면',keywords:'숏폼·자동',d:'content'},
 {label:'썸네일 만드는 화면',keywords:'썸네일·생성',d:'content'},
 {label:'카드뉴스 생성기',keywords:'카드뉴스·생성',d:'content'},
 {label:'크롬 확장 프로그램',keywords:'확장·크롬',d:'general'},
 {label:'링크 모음 한 페이지',keywords:'링크·프로필',d:'general'},
 {label:'매출 한눈에 보는 대시보드',keywords:'매출·대시보드',d:'biz'},
 {label:'사진 찍으면 결과 나오는 화면',keywords:'카메라·결과',d:'general'},
 {label:'뒤집는 플래시카드 앱',keywords:'카드·암기',d:'learn'},
 {label:'챗봇 하나 (카톡·왓츠앱)',keywords:'챗봇·메신저',d:'general'},
 {label:'사진 올려 만드는 굿즈',keywords:'개인화·제작',d:'image'},
 {label:'체크리스트 화면 하나',keywords:'체크·목록',d:'general'},
 {label:'손글씨 노트장',keywords:'노트·필기',d:'learn'},
 {label:'가족 공유 캘린더',keywords:'캘린더·공유',d:'life'},
 {label:'운동 영상 목록',keywords:'영상·운동',d:'health'},
 {label:'하루 식단 기록장',keywords:'식단·기록',d:'health'},
 {label:'스캔 문서 보관함',keywords:'스캔·문서',d:'work'},
 {label:'회의 요약 카드',keywords:'회의·요약',d:'work'},
 {label:'기분 색칠 캘린더',keywords:'기분·달력',d:'life'},
 {label:'습관 체크판',keywords:'습관·체크',d:'learn'},
 {label:'사주 결과 카드',keywords:'운세·결과',d:'life'},
 {label:'QR 스캔 카메라 화면',keywords:'QR·스캔',d:'general'},
 {label:'친구끼리 송금하는 화면',keywords:'송금·간편',d:'money'}]},
{key:'scene',ko:'장면',question:'언제·어디서?',glyph:'📍',opt:true,cards:[
 {label:'출근길 지하철에서',keywords:'지하철 · 출근 · 아침'},
 {label:'잠들기 직전 침대에서',keywords:'침대 · 밤 · 취침'},
 {label:'점심시간 회사 근처에서',keywords:'점심 · 회사 · 낮'},
 {label:'퇴근 후 소파에 앉아',keywords:'소파 · 저녁 · 퇴근'},
 {label:'아침에 눈 뜨자마자',keywords:'기상 · 아침 · 침대'},
 {label:'카페에서 커피 기다리며',keywords:'카페 · 커피 · 대기'},
 {label:'엘리베이터 기다리는 동안',keywords:'엘리베이터 · 짬 · 대기'},
 {label:'야근하다 잠깐 쉴 때',keywords:'야근 · 휴식 · 밤'},
 {label:'저녁 설거지 끝내고',keywords:'설거지 · 집 · 저녁'},
 {label:'버스 창가 자리에서',keywords:'버스 · 이동 · 창밖'},
 {label:'러닝머신 위에서 뛰며',keywords:'헬스장 · 운동 · 러닝'},
 {label:'산책하다 벤치에 앉아',keywords:'산책 · 공원 · 휴식'},
 {label:'샤워하고 머리 말리며',keywords:'샤워 · 화장실 · 준비'},
 {label:'혼밥하며 영상 볼 때',keywords:'혼밥 · 식사 · 영상'},
 {label:'주말 늦잠 자고 난 오전',keywords:'주말 · 늦잠 · 오전'},
 {label:'회의 시작 전 자리에서',keywords:'회의 · 사무실 · 대기'},
 {label:'밤늦게 야식 먹고 나서',keywords:'야식 · 심야 · 집'},
 {label:'세탁기 돌아가길 기다리며',keywords:'세탁 · 집안일 · 대기'},
 {label:'화장실 변기에 앉아',keywords:'화장실 · 짬 · 혼자'}]},
{key:'mind',ko:'마음',question:'사람 마음의 습관',glyph:'🧠',opt:true,cards:[
 {label:'한 번 시작하면<br>끝내고 싶어져요 (자이가르닉 효과)',keywords:'미완성 · 완결 · 집착'},
 {label:'남들 다 하니까<br>나도 하게 돼요 (사회적 증거)',keywords:'군중 · 따라하기 · 대세'},
 {label:'공짜로 받으면<br>갚고 싶어져요 (상호성 원리)',keywords:'보답 · 호의 · 부담'},
 {label:'손해 보는 게<br>제일 싫어요 (손실 회피)',keywords:'손해 · 두려움 · 회피'},
 {label:'이미 시작했으니<br>계속하게 돼요 (매몰비용 오류)',keywords:'본전 · 지속 · 아까움'},
 {label:'곧 끝난다니까<br>더 급해져요 (희소성 효과)',keywords:'마감 · 한정 · 조급'},
 {label:'눈앞의 작은 보상에<br>약해요 (현재 편향)',keywords:'즉시 · 보상 · 유혹'},
 {label:'내가 정한 건<br>더 소중해 보여요 (보유 효과)',keywords:'내것 · 애착 · 소유'},
 {label:'남과 자꾸<br>비교하게 돼요 (사회 비교)',keywords:'비교 · 남들 · 경쟁'},
 {label:'처음 본 정보에<br>끌려가요 (앵커링 효과)',keywords:'기준점 · 첫인상 · 판단'},
 {label:'말로 뱉으면<br>지키게 돼요 (일관성 원리)',keywords:'약속 · 선언 · 실천'},
 {label:'완성 직전이면<br>더 하고 싶어요 (목표 근접 효과)',keywords:'막판 · 완성 · 몰입'},
 {label:'콕 집어 정하면<br>실행하게 돼요 (실행 의도)',keywords:'계획 · 구체 · 실행'},
 {label:'작게 쪼개면<br>부담이 줄어요 (청킹)',keywords:'작게 · 분할 · 시작'},
 {label:'기록하면<br>더 지키게 돼요 (자기 관찰 효과)',keywords:'기록 · 점검 · 습관'},
 {label:'좋아하는 사람<br>따라 하게 돼요 (호감 원리)',keywords:'호감 · 모방 · 신뢰'},
 {label:'자주 보이면<br>좋아지게 돼요 (단순 노출 효과)',keywords:'반복 · 익숙 · 친근'},
 {label:'누가 보면<br>더 잘하게 돼요 (관찰자 효과)',keywords:'시선 · 긴장 · 분발'},
 {label:'칭찬받으면<br>더 하고 싶어요 (강화 효과)',keywords:'칭찬 · 보상 · 동기'}]},
];
var TEMPLATE="{scene}, '{pain}'라고 느끼는 {who}를 위해. {form} 형태로 {how} — '{mind}' 심리를 활용해요.";
