#!/usr/bin/env python3
import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import numpy as np


DEFAULT_LOCAL_MODEL = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
DEFAULT_OPENAI_MODEL = "text-embedding-3-small"


def parse_args():
    parser = argparse.ArgumentParser(description="Check semantic similarity across idea combinations.")
    parser.add_argument("--input", required=True, help="JSONL generated by export-idea-lab-combinations.mjs")
    parser.add_argument("--output", default=None, help="Write JSON results to this path instead of stdout")
    parser.add_argument(
        "--mode",
        choices=("source-fidelity", "portfolio"),
        default="source-fidelity",
        help="Compare each idea with its overseas source, or compare ideas with one another.",
    )
    parser.add_argument("--provider", choices=("local", "openai"), default="local")
    parser.add_argument("--model", default=None)
    parser.add_argument("--api-key-env", default="ALLSALE_OPEN_AI_KEY")
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--cache-dir", default=None)
    parser.add_argument("--top", type=int, default=50)
    parser.add_argument(
        "--focus-scenario-ids",
        default=None,
        help="Comma-separated scenario IDs whose nearest cross-scenario neighbors should be reported separately.",
    )
    parser.add_argument("--cross-review", type=float, default=None)
    parser.add_argument("--cross-critical", type=float, default=None)
    parser.add_argument("--within-review", type=float, default=None)
    parser.add_argument("--within-critical", type=float, default=None)
    parser.add_argument("--fidelity-min", type=float, default=0.80)
    parser.add_argument("--fidelity-target-max", type=float, default=0.99)
    return parser.parse_args()


def load_records(path):
    records = []
    with Path(path).open(encoding="utf-8") as stream:
        for line in stream:
            if line.strip():
                records.append(json.loads(line))
    if not records:
        raise ValueError("No combination records found.")
    return records


def normalize(matrix):
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    return matrix / np.clip(norms, 1e-12, None)


def embed_local(texts, model_name, batch_size, cache_dir):
    from fastembed import TextEmbedding

    kwargs = {"model_name": model_name, "cache_dir": cache_dir}
    if cache_dir is None:
        kwargs.pop("cache_dir")
    model = TextEmbedding(**kwargs)
    return np.asarray(list(model.embed(texts, batch_size=batch_size)))


def openai_request(url, headers, payload, attempts=5):
    encoded = json.dumps(payload).encode("utf-8")
    for attempt in range(attempts):
        request = urllib.request.Request(url, data=encoded, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                return json.load(response)
        except urllib.error.HTTPError as error:
            retryable = error.code in (408, 409, 429) or error.code >= 500
            if not retryable or attempt == attempts - 1:
                detail = error.read().decode("utf-8", errors="replace")[:500]
                raise RuntimeError(f"OpenAI embeddings request failed ({error.code}): {detail}") from error
        except urllib.error.URLError as error:
            if attempt == attempts - 1:
                raise RuntimeError(f"OpenAI embeddings request failed: {error.reason}") from error
        time.sleep(min(2**attempt, 8))
    raise RuntimeError("OpenAI embeddings request failed after retries.")


def embed_openai(texts, model_name, batch_size, api_key_env):
    api_key = os.environ.get(api_key_env)
    if not api_key:
        raise RuntimeError(f"Environment variable {api_key_env} is missing.")
    url = "https://api.openai.com/v1/embeddings"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    vectors = []
    for start in range(0, len(texts), batch_size):
        batch = texts[start : start + batch_size]
        result = openai_request(
            url,
            headers,
            {"model": model_name, "input": batch, "encoding_format": "float"},
        )
        ordered = sorted(result["data"], key=lambda item: item["index"])
        vectors.extend(item["embedding"] for item in ordered)
    return np.asarray(vectors)


def percentile_summary(values):
    if values.size == 0:
        return {}
    percentiles = [50, 75, 90, 95, 99, 99.5, 99.9, 99.95, 99.99, 100]
    return {str(p): round(float(np.percentile(values, p)), 6) for p in percentiles}


def top_scenario_groups(records, rows, cols, values, limit, outlier_threshold):
    grouped = {}
    for left, right, similarity in zip(rows, cols, values):
        left_record, right_record = records[int(left)], records[int(right)]
        scenario_pair = tuple(sorted((left_record["scenarioId"], right_record["scenarioId"])))
        current = grouped.setdefault(
            scenario_pair,
            {"maxSimilarity": -1.0, "outlierCount": 0, "topPair": None},
        )
        if similarity >= outlier_threshold:
            current["outlierCount"] += 1
        if similarity > current["maxSimilarity"]:
            current["maxSimilarity"] = float(similarity)
            current["topPair"] = pair_payload(records, left, right, similarity)
    ordered = sorted(grouped.items(), key=lambda item: item[1]["maxSimilarity"], reverse=True)
    return [
        {
            "scenarioIds": list(scenario_pair),
            "maxSimilarity": round(payload["maxSimilarity"], 6),
            "outlierCount": payload["outlierCount"],
            "topPair": payload["topPair"],
        }
        for scenario_pair, payload in ordered[:limit]
    ]


def top_within_scenarios(records, rows, cols, values, limit, outlier_threshold):
    grouped = {}
    for left, right, similarity in zip(rows, cols, values):
        scenario_id = records[int(left)]["scenarioId"]
        current = grouped.setdefault(
            scenario_id,
            {"maxSimilarity": -1.0, "outlierCount": 0, "topPair": None},
        )
        if similarity >= outlier_threshold:
            current["outlierCount"] += 1
        if similarity > current["maxSimilarity"]:
            current["maxSimilarity"] = float(similarity)
            current["topPair"] = pair_payload(records, left, right, similarity)
    ordered = sorted(grouped.items(), key=lambda item: item[1]["maxSimilarity"], reverse=True)
    return [
        {
            "scenarioId": scenario_id,
            "maxSimilarity": round(payload["maxSimilarity"], 6),
            "outlierCount": payload["outlierCount"],
            "topPair": payload["topPair"],
        }
        for scenario_id, payload in ordered[:limit]
    ]


def pair_payload(records, left, right, similarity):
    a, b = records[int(left)], records[int(right)]
    return {
        "similarity": round(float(similarity), 6),
        "left": {
            "id": a["id"],
            "scenarioId": a["scenarioId"],
            "sourceName": a["sourceName"],
            "payer": a["payer"],
            "moment": a["moment"],
            "twistTitles": a["twistTitles"],
        },
        "right": {
            "id": b["id"],
            "scenarioId": b["scenarioId"],
            "sourceName": b["sourceName"],
            "payer": b["payer"],
            "moment": b["moment"],
            "twistTitles": b["twistTitles"],
        },
    }


def top_pairs(records, rows, cols, values, limit):
    if values.size == 0:
        return []
    count = min(limit, values.size)
    candidates = np.argpartition(values, -count)[-count:]
    ordered = candidates[np.argsort(values[candidates])[::-1]]
    return [pair_payload(records, rows[index], cols[index], values[index]) for index in ordered]


def fidelity_payload(record, similarity):
    return {
        "similarity": round(float(similarity), 6),
        "id": record["id"],
        "scenarioId": record["scenarioId"],
        "sourceName": record["sourceName"],
        "payer": record["payer"],
        "moment": record["moment"],
        "twistTitles": record["twistTitles"],
    }


def emit_output(payload, output_path):
    rendered = json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    if output_path:
        Path(output_path).write_text(rendered, encoding="utf-8")
    else:
        sys.stdout.write(rendered)


def source_fidelity_output(args, records, model_name, embed):
    source_records = {}
    for record in records:
        source_records.setdefault(record["scenarioId"], record["sourceText"])
    source_ids = list(source_records)
    source_index = {scenario_id: index for index, scenario_id in enumerate(source_ids)}
    fidelity_texts = [record["fidelityText"] for record in records]
    texts = fidelity_texts + [source_records[scenario_id] for scenario_id in source_ids]
    vectors = normalize(embed(texts).astype(np.float32, copy=False))
    combination_vectors = vectors[: len(records)]
    source_vectors = vectors[len(records) :]
    similarities = np.asarray(
        [
            combination_vectors[index] @ source_vectors[source_index[record["scenarioId"]]]
            for index, record in enumerate(records)
        ]
    )
    ordered = np.argsort(similarities)
    low_count = min(args.top, len(records))
    high_count = min(args.top, len(records))
    below = similarities < args.fidelity_min
    target = (similarities >= args.fidelity_min) & (
        similarities <= args.fidelity_target_max
    )
    exact_allowed = similarities > args.fidelity_target_max
    return {
        "mode": "source-fidelity",
        "model": {
            "provider": args.provider,
            "name": model_name,
            "dimension": int(vectors.shape[1]),
            "normalization": "L2",
            "similarity": "cosine via normalized dot product",
        },
        "scope": {
            "combinations": len(records),
            "scenarios": len(source_ids),
            "singleTwist": sum(record["twistCount"] == 1 for record in records),
            "doubleTwist": sum(record["twistCount"] == 2 for record in records),
        },
        "policy": {
            "minimum": args.fidelity_min,
            "targetMaximum": args.fidelity_target_max,
            "aboveTargetMaximum": "allowed because an overseas product mechanic may be copied exactly",
            "portfolioDuplicates": "allowed and not evaluated in this mode",
        },
        "summary": {
            "percentiles": percentile_summary(similarities),
            "belowMinimum": int(np.count_nonzero(below)),
            "inTargetBand": int(np.count_nonzero(target)),
            "exactAllowed": int(np.count_nonzero(exact_allowed)),
            "pass": int(np.count_nonzero(~below)),
            "passRate": round(float(np.count_nonzero(~below) / len(records)), 6),
        },
        "lowest": [fidelity_payload(records[int(index)], similarities[index]) for index in ordered[:low_count]],
        "highest": [
            fidelity_payload(records[int(index)], similarities[index])
            for index in ordered[-high_count:][::-1]
        ],
    }


def main():
    args = parse_args()
    records = load_records(args.input)
    model_name = args.model or (
        DEFAULT_OPENAI_MODEL if args.provider == "openai" else DEFAULT_LOCAL_MODEL
    )
    if args.provider == "openai":
        embed = lambda texts: embed_openai(texts, model_name, args.batch_size, args.api_key_env)
    else:
        embed = lambda texts: embed_local(texts, model_name, args.batch_size, args.cache_dir)

    if args.mode == "source-fidelity":
        emit_output(source_fidelity_output(args, records, model_name, embed), args.output)
        return

    texts = [record["text"] for record in records]
    vectors = embed(texts)
    vectors = normalize(vectors.astype(np.float32, copy=False))

    similarities = vectors @ vectors.T
    rows, cols = np.triu_indices(len(records), k=1)
    values = similarities[rows, cols]
    scenario_ids = np.asarray([record["scenarioId"] for record in records])
    cross_mask = scenario_ids[rows] != scenario_ids[cols]
    within_mask = ~cross_mask

    cross_rows, cross_cols, cross_values = rows[cross_mask], cols[cross_mask], values[cross_mask]
    within_rows, within_cols, within_values = rows[within_mask], cols[within_mask], values[within_mask]
    cross_outlier_threshold = float(np.percentile(cross_values, 99.9))
    within_outlier_threshold = float(np.percentile(within_values, 99.9))
    cross_review = args.cross_review if args.cross_review is not None else cross_outlier_threshold
    cross_critical = (
        args.cross_critical
        if args.cross_critical is not None
        else float(np.percentile(cross_values, 99.99))
    )
    within_review = args.within_review if args.within_review is not None else within_outlier_threshold
    within_critical = (
        args.within_critical
        if args.within_critical is not None
        else float(np.percentile(within_values, 99.99))
    )

    output = {
        "mode": "portfolio",
        "model": {
            "provider": args.provider,
            "name": model_name,
            "dimension": int(vectors.shape[1]),
            "normalization": "L2",
            "similarity": "cosine via normalized dot product",
        },
        "scope": {
            "combinations": len(records),
            "scenarios": len(set(scenario_ids.tolist())),
            "singleTwist": sum(record["twistCount"] == 1 for record in records),
            "doubleTwist": sum(record["twistCount"] == 2 for record in records),
            "allPairs": int(values.size),
            "crossScenarioPairs": int(cross_values.size),
            "withinScenarioPairs": int(within_values.size),
        },
        "thresholds": {
            "defaultMethod": "empirical p99.9 review / p99.99 critical unless explicitly overridden",
            "crossScenario": {
                "review": round(cross_review, 6),
                "critical": round(cross_critical, 6),
            },
            "withinScenario": {
                "review": round(within_review, 6),
                "critical": round(within_critical, 6),
            },
        },
        "crossScenario": {
            "percentiles": percentile_summary(cross_values),
            "outlierThreshold": round(cross_outlier_threshold, 6),
            "reviewCount": int(np.count_nonzero(cross_values >= cross_review)),
            "criticalCount": int(np.count_nonzero(cross_values >= cross_critical)),
            "topScenarioPairs": top_scenario_groups(
                records,
                cross_rows,
                cross_cols,
                cross_values,
                min(args.top, 30),
                cross_outlier_threshold,
            ),
            "topPairs": top_pairs(records, cross_rows, cross_cols, cross_values, args.top),
        },
        "withinScenario": {
            "percentiles": percentile_summary(within_values),
            "outlierThreshold": round(within_outlier_threshold, 6),
            "reviewCount": int(np.count_nonzero(within_values >= within_review)),
            "criticalCount": int(np.count_nonzero(within_values >= within_critical)),
            "topScenarios": top_within_scenarios(
                records,
                within_rows,
                within_cols,
                within_values,
                min(args.top, 30),
                within_outlier_threshold,
            ),
            "topPairs": top_pairs(records, within_rows, within_cols, within_values, args.top),
        },
    }
    focus_ids = {
        scenario_id.strip()
        for scenario_id in (args.focus_scenario_ids or "").split(",")
        if scenario_id.strip()
    }
    if focus_ids:
        missing_focus_ids = sorted(focus_ids - set(scenario_ids.tolist()))
        if missing_focus_ids:
            raise ValueError(
                f"Focus scenario IDs are missing from input: {', '.join(missing_focus_ids)}"
            )
        focus_mask = cross_mask & (
            np.isin(scenario_ids[rows], list(focus_ids))
            | np.isin(scenario_ids[cols], list(focus_ids))
        )
        focus_rows = rows[focus_mask]
        focus_cols = cols[focus_mask]
        focus_values = values[focus_mask]
        output["focusScenarios"] = {
            "scenarioIds": sorted(focus_ids),
            "pairs": int(focus_values.size),
            "percentiles": percentile_summary(focus_values),
            "reviewCount": int(np.count_nonzero(focus_values >= cross_review)),
            "criticalCount": int(np.count_nonzero(focus_values >= cross_critical)),
            "topScenarioPairs": top_scenario_groups(
                records,
                focus_rows,
                focus_cols,
                focus_values,
                min(args.top, 30),
                cross_outlier_threshold,
            ),
            "topPairs": top_pairs(
                records,
                focus_rows,
                focus_cols,
                focus_values,
                args.top,
            ),
        }
    emit_output(output, args.output)


if __name__ == "__main__":
    main()
